---
- block:
    - name: Allow rhsm a longer timeout to help out with subscription-manager
      lineinfile:
        dest: /etc/rhsm/rhsm.conf
        line: 'server_timeout=600'
        insertafter: '^proxy_password ='

    - name: RedHat subscriptions
      redhat_subscription:
        username: "{{ rhsm_user }}"
        password: "{{ rhsm_password }}"
      when: "'Current' not in subscribed.stdout and rhsm_user is defined and rhsm_user"

    - name: Attach to OpenShift Pool
      command: subscription-manager subscribe --pool {{ rhsm_pool }}
      ignore_errors: yes

  when: ansible_distribution == "RedHat"

